basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /kill:
    get:
      description: Kill all the running tasks
      responses:
        "200":
          description: kill all the tasks
          schema:
            type: string
      summary: Kill all the running tasks
swagger: "2.0"
